name: Build Go Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Specify the Go version you want to use

      - name: execute tests
        run: go test ./...

      - name: Build Go binaries
        run: |
          GOARCH=amd64 GOOS=linux go build -ldflags "-s -w" -o gupdate-linux-amd64
          GOARCH=arm64 GOOS=linux go build -ldflags "-s -w" -o gupdate-linux-arm64
          GOARCH=amd64 GOOS=darwin go build -ldflags "-s -w" -o gupdate-darwin-amd64
          GOARCH=arm64 GOOS=darwin go build -ldflags "-s -w" -o gupdate-darwin-arm64

      - name: Upload binary and build release
        uses: softprops/action-gh-release@v2
        with:
          files: gupdate-*
          tag_name: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
